/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/car.glb
*/

import React, { forwardRef, useImperativeHandle, useMemo, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { Group, Mesh, type Material } from "three";

export interface CarRef {
  backWheel: React.RefObject<Group>;
  frontLeftWheel: React.RefObject<Group>;
  frontRightWheel: React.RefObject<Group>;
}

const MODEL_PATH = "./models/Sport-Car.glb";

function WheelPrimitive({
  nodeName,
  outerRef,
}: {
  nodeName: string;
  outerRef: React.RefObject<Group>;
}) {
  const { scene } = useGLTF(MODEL_PATH);

  const cloned = useMemo(() => {
    const original = scene.getObjectByName(nodeName);
    if (!original) return null;
    const clone = original.clone(true);
    const pos = original.position.clone();
    clone.position.set(0, 0, 0);
    return { clone, pos };
  }, [scene, nodeName]);

  if (!cloned) return null;

  return (
    <group ref={outerRef} position={cloned.pos}>
      <primitive object={cloned.clone} />
    </group>
  );
}

export const Model = forwardRef<CarRef>(function Model(props, ref) {
  const { nodes, materials } = useGLTF(MODEL_PATH) as unknown as {
    nodes: Record<string, Mesh>;
    materials: Record<string, Material>;
  };

  const backWheelRef = useRef<Group>(null!);
  const frontLeftWheelRef = useRef<Group>(null!);
  const frontRightWheelRef = useRef<Group>(null!);

  useImperativeHandle(ref, () => ({
    backWheel: backWheelRef,
    frontLeftWheel: frontLeftWheelRef,
    frontRightWheel: frontRightWheelRef,
  }));

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes["SportsCar_Cube005-Mesh"].geometry}
        material={materials.Orange}
      />
      <mesh
        geometry={nodes["SportsCar_Cube005-Mesh_1"].geometry}
        material={materials.DarkOrange}
      />
      <mesh
        geometry={nodes["SportsCar_Cube005-Mesh_2"].geometry}
        material={materials.Windows}
      />
      <mesh
        geometry={nodes["SportsCar_Cube005-Mesh_3"].geometry}
        material={materials.Grey}
      />
      <mesh
        geometry={nodes["SportsCar_Cube005-Mesh_4"].geometry}
        material={materials.Headlights}
      />
      <mesh
        geometry={nodes["SportsCar_Cube005-Mesh_5"].geometry}
        material={materials.TailLights}
      />

      <WheelPrimitive
        nodeName="SportsCar_BackWheels_Cylinder004"
        outerRef={backWheelRef}
      />
      <WheelPrimitive
        nodeName="SportsCar_FrontLeftWheel_Cylinder013"
        outerRef={frontLeftWheelRef}
      />
      <WheelPrimitive
        nodeName="SportsCar_FrontRightWheel_Cylinder014"
        outerRef={frontRightWheelRef}
      />
    </group>
  );
});

useGLTF.preload(MODEL_PATH);
